spring:
  application:
    name: ms-books-elasticsearch

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-books-elasticsearch

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method

server:
  port: 0

elasticsearch:
  endpoint: unir-search-443549085.us-east-1.bonsaisearch.net
  credentials:
    user: h5hd9e1z97
    password: g3lxbcv1zg